### ISSUE TITLE
 extend to asset and link objects

### ISSUE THREAD

**Issue by tomkralidis** [stac-extensions/timestamps#4]
We would like to display file timestamps not only for item properties but for assets and links as well.

As a user I would like to see timestamps for given assets and links so that I can visually assess how old some files are.

**Comment by m-mohr** [comment]
Just a quick note: It is already possible to use these for assets, but it's not yet possible for links.

**Comment by m-mohr** [comment]
A new use case came up: Adding created/updated fields to item links so that you know whether you need to ingest the data or not.

**Comment by m-mohr** [comment]
Implemented in v1.1 @tomkralidis
