### ISSUE TITLE
Can this be used to define dates for a collection?

### ISSUE THREAD

**Issue by keul** [stac-extensions/timestamps#7]
Although the scope of the extension define to be usable on collections and not only items, looking at the JSON schema it seems is only usable inside the `assets` structure or in a `item_assets`, which is seems related to https://github.com/stac-extensions/item-assets.

1. is this extension compatible to define dates on a single collection? For example: I want to define when a collection has been published, or last modified.
2. I think that an example of usage on collection would be useful too (now examples dir only contains an item example)

**Comment by m-mohr** [comment]
Yes, that's the intention, but it seems we failed to correctly add that to the schema.

**Comment by keul** [comment]
Another nice addition would be to backport some dates already defined for items (like `created`, `updated`) for collections too

**Comment by m-mohr** [comment]
Yes, created and updated are meant to be usable in Collections. The collection JSON Schema doesn't use any of the common metadata fields for validation yet - something to be fixed. Please fill an issue in the stac-spec repo.

**Comment by m-mohr** [comment]
Implemented in v1.1 @keul
